name: Mirror Source Repository

on:
  push:
    paths-ignore:
      - '.github/workflows/sync.yml'
    branches:
      - main
      
jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Push to Destination Repository
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote add destination https://github.com/asishrj91/Test2.git
          git push destination --mirror
        env:
          PAT_GITHUB: ${{ secrets.newpattoken }}
