name: CI

on:
  push:
    paths-ignore:
      - '.github/workflows/sync.yml'
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: List all changed files with preceding folder
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # Use 'dirname' to extract the directory path, and then 'basename' to get the parent directory name
            folder=$(dirname "$file" | xargs basename)
            echo "$file was changed in folder '$folder'"
            if [[ $folder == Se* ]]; then
              preceding_folder_path=$(dirname $(dirname "$file"))
              echo "preceding folder path is '$preceding_folder_path'"
              preceding_folder=$(basename "$preceding_folder_path")
              echo "preceding folder is '$preceding_folder'"
            fi
          done
      - name: Create Artifact Directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/artifacts/$preceding_folder
          cp $GITHUB_WORKSPACE/$preceding_folder_path $GITHUB_WORKSPACE/artifacts/$preceding_folder/
        working-directory: ${{ github.workspace }}

      - name: Archive Artifact
        uses: actions/upload-artifact@v2
        with:
         name: my-artifact
         path: ${{ github.workspace }}/artifacts
