name: CI

on:
  push:
    branches:
      - main

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: List all changed files with preceding folder
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # Use 'dirname' to extract the directory path, and then 'basename' to get the parent directory name
            folder=$(dirname "$file" | xargs basename)
            echo "$file was changed in folder '$folder'"
		IFS='/' read -ra dirs <<< "$file"
            
            # Check if 'Second' is in the path and find the index
            for i in "${!dirs[@]}"; do
              if [[ ${dirs[i]} == "wo*" ]]; then
                # Check if there is a preceding folder
                if [ $i -gt 0 ]; then
                  preceding_folder="${dirs[i-1]}"
                  echo "Preceding folder of 'Second' is '$preceding_folder'"
                else
                  echo "No preceding folder for 'Second' (it is a top-level folder)"
                fi
                break
              fi
            done
          done

