name: Create Artifact

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Print the variable
      run: echo "The value of workspace is ${{ github.workspace }}}"
    - name: Create Artifact Directory
      run: |
        mkdir -p $GITHUB_WORKSPACE/artifacts/Second_Folder
        cp $GITHUB_WORKSPACE/Test1/First_Folder/Second_Folder/Text_doc.txt $GITHUB_WORKSPACE/artifacts/Second_Folder/
      working-directory: ${{ github.workspace }}

    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ${{ github.workspace }}/artifacts
