name: Sync Repositories

on:
  push:
    branches:
      - main  # Change this to your source branch (e.g., main, master, etc.)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        repository: asishrj91/Test1  # Change to your source repository URL

    - name: Push to destination repository
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git remote add destination https://github.com/asishrj91/Test2.git  # Change to your destination repository URL
        git push destination main  # Change to your destination branch (e.g., main, master, etc.)

    - name: Complete
      run: echo "Sync complete"
