name: Locate Changes

on:
  push:
    branches:
      - main  # Change this to your branch name

jobs:
  locate_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Get list of changed files
        id: changed_files
        run: |
          FROM_COMMIT=${{ github.event.before }}
          TO_COMMIT=${{ github.sha }}
          CHANGED_FILES=$(git diff --name-only $FROM_COMMIT $TO_COMMIT)
          echo "Changed Files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Locate changes
        id: locate_changes
        run: |
          CHANGED_FILES=(${{ env.CHANGED_FILES }})
          for file in "${CHANGED_FILES[@]}"; do
            # Process each changed file here
            # You can use 'grep' or any other tool to locate changes in the file
            # For example, to find specific text within the file:
            if grep -q "your_pattern" $file; then
              echo "Changes found in $file"
              # You can add more actions here
            fi
          done
