name: Create ZIP and Save to Artifacts

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create ZIP
      run: |
        mkdir -p $GITHUB_WORKSPACE/artifacts
        zip -r $GITHUB_WORKSPACE/artifacts/First_Folder/Second_Folder.zip Test1/First_Folder/Second_Folder
      working-directory: ${{ github.workspace }}

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-zip-artifact
        path: ${{ github.workspace }}/artifacts

