name: Create Artifacts

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  create-artifacts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Artifacts
      run: |
        mkdir -p artifacts/Second_Folder
        cp Test1/First_Folder/Second_Folder/Text_doc.txt artifacts/Second_Folder/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifacts
        path: ./artifacts
